const TeamData = [
  {
    img: "",
    name: "Shreyash Khandagle",
    Profession: "WebMaster",
    git: "https://github.com/Girish345",
    linkdin: "https://github.com/Girish345",
    instagram: "https://github.com/Girish345",
  },
  {
    img: "/Developers/Yash.jpg",
    name: "Yash Waghmare",
    Profession: "WebMaster",
    git: "https://github.com/Yash-Waghmare",
    linkdin: "https://www.linkedin.com/in/yash-waghmare-7b8b51201/",
    instagram: "https://instagram.com/yash_7714?igshid=ZDdkNTZiNTM=",
  },
  {
    img: "/Developers/Suraj.jpg",
    name: "Suraj Tade",
    Profession: "WebMaster",
    git: "github.com/surajTade",
    linkdin: "https://www.linkedin.com/in/suraj-tade",
    instagram: " https://instagram.com/suraj__tade?igshid=ZDdkNTZiNTM=",
  },
  {
    img: "/Developers/sarthak2.jpeg",
    name: "Sarthak Joshi",
    Profession: "Developer",
    git: "https://github.com/sarthak-subhash-joshi",
    linkdin: "https://www.linkedin.com/in/sarthak-joshi-6112b7231/",
    instagram: "https://www.instagram.com/sarthak_joshi_3011/",
  },
  {
    img: "/Developers/girishnew.jpeg",
    name: "Girish Bhosale",
    Profession: "Developer",
    git: "https://github.com/Girish345",
    linkdin: "https://github.com/Girish345",
    instagram: "https://github.com/Girish345",
  },
  {
    img: "/Developers/Atharva.jpg",
    name: "Atharva Pande",
    Profession: "Developer",
    git: "https://github.com/atharvapande45",
    linkdin: "https://www.linkedin.com/in/atharva-pande-855341244",
    instagram: "https://instagram.com/atharvapande45?igshid=ZDdkNTZiNTM=",
  },
  {
    img: "/Developers/aditya.jpg",
    name: "Aditya Lad",
    Profession: "Jr. WebMaster",
    git: "https://github.com/Adityalad-25",
    linkdin: "https://www.linkedin.com/in/aditya-lad-609586226",
    instagram: "https://instagram.com/_adi_ty_a?igshid=ZDdkNTZiNTM=",
  },
  {
    img: "/Developers/sejal.jpg",
    name: "Sejal Rahane",
    Profession: "Jr. WebMaster",
    git: "https://github.com/sejalrahane",
    linkdin: "https://www.linkedin.com/in/sejal-rahane-094447193",
    instagram: "https://instagram.com/sejal_rahane_?igshid=MTA2NDdkNWE=",
  },
  {
    img: "/Developers/Chetan.jpg",
    name: "Chetan Padhen",
    Profession: "Jr. WebMaster",
    git: " https://github.com/Chetax",
    linkdin: "https://www.linkedin.com/in/chetan-padhen-501416222/",
    instagram: "",
  },
  {
    img: "/Developers/mrudul.jpg",
    name: "Mrudul Ahirrao",
    Profession: "Jr. WebMaster",
    git: "https://github.com/MrudulAhirrao",
    linkdin: "https://in.linkedin.com/in/mrudul-ahirrao-133088216",
    instagram: "https://www.instagram.com/mrudul.ahirrao/",
  },
  {
    img: "/Developers/pranav.jpeg",
    name: "Pranav Kulkarni",
    Profession: "Jr. WebMaster",
    git: "https://www.github.com/pranavkulkarni2905",
    linkdin: "https://www.linkedin.com/in/pranavk2905",
    instagram: "https://instagram.com/i_am_pranavkulkarni?igshid=ZDdkNTZiNTM=",
  },
  {
    img: "/Developers/shraddha.jpg",
    name:"Shradha Yeole",
    Profession: "Jr. WebMaster",
    git: "https://github.com/MrudulAhirrao",
    linkdin: "https://www.linkedin.com/in/shraddha-yeole-8519161b4/",
    instagram: "https://instagram.com/shradha_1602?igshid=ZDdkNTZiNTM=",
  },
  {
    img: "/Developers/Tarun.jpeg",
    name: "Tarun Rathod",
    Profession: "Jr. WebMaster",
    git: "https://github.com/tarunnnrathoddd",
    linkdin: "https://www.linkedin.com/in/tarun-rathod-aa7ab7223",
    instagram: "https://www.instagram.com/_.tarunnn.rathoddd._",
  },
  {
    img: "/Developers/Kanak.jpg",
    name: "Kanak Agarwal",
    Profession: "Jr. WebMaster",
    git: "https://github.com/kanak8403",
    linkdin: "https://www.linkedin.com/in/kanak-agrawal-78791a259/",
    instagram: "https://www.instagram.com/kanakagrawal08/. ",
  }
];

export default TeamData;
