import { aboutBGM } from "../assets";
const cardData = [
	{
		id: 1,
		event_name: "Codigo 3.0",
		date: "",
		short_description: "abc",
		detailed_description: "prq",
		image: aboutBGM,
		path: "/codigo",
	},

	{
		id: 2,
		event_name: "Webbit-2.0",
		date: "",
		short_description: "abc",
		detailed_description: "prq",
		image: aboutBGM,
		path: "/webbit",
	},
	{
		id: 3,
		event_name: "Perplexo",
		date: "",
		short_description: "abc",
		detailed_description: "prq",
		image: aboutBGM,
		path: "/Perplexo",
	},
	{
		id: 4,
		event_name: "Hackathon",
		date: "",
		short_description: "abc",
		detailed_description: "prq",
		image: aboutBGM,
		path: "/hackathon",
	},
	{
		id: 5,
		event_name: "Cosmic Aptitude Test",
		date: "",
		short_description: "abc",
		detailed_description: "prq",
		image: aboutBGM,
		path: "/cosmic_Aptitude_Test",
	},
	{
		id: 6,
		event_name: "IPL Auction",
		date: "",
		short_description: "abc",
		detailed_description: "prq",
		image: aboutBGM,
		path: "/IPL_Auction",
	},
	{
		id: 7,
		event_name: "Startup Mania",
		date: "",
		short_description: "abc",
		detailed_description: "prq",
		image: aboutBGM,
		path: "/Startup_Mania",
	},
	{
		id: 8,
		event_name: "The Alpha Analyst",
		date: "",
		short_description: "abc",
		detailed_description: "prq",
		image: aboutBGM,
		path: "/The_Alpha_Analyst",
	},
	{
		id: 9,
		event_name: "G20x Anantya",
		date: "",
		short_description: "abc",
		detailed_description: "prq",
		image: aboutBGM,
		path: "/G20x_Anantya",
	},
	{
		id: 10,
		event_name: "Movie Trivia",
		date: "",
		short_description: "abc",
		detailed_description: "prq",
		image: aboutBGM,
		path: "/Movie_Trivia",
	},
	{
		id: 11,
		event_name: "Unleash the Art ",
		date: "",
		short_description: "abc",
		detailed_description: "prq",
		image: aboutBGM,
		path: "/Unleash_the_Art",
	},
	{
		id: 12,
		event_name: "Sports League ",
		date: "",
		short_description: "abc",
		detailed_description: "prq",
		image: aboutBGM,
		path: "/Sports_League",
	},
];

export default cardData;
