const TeamData = [
  {
    img: "/Developers/shreyash.jpg",
    name: "Shreyash Khandagle",
    Profession: "WebMaster",
    git: "https://github.com/Shreyashk-07",
    linkdin: "https://www.linkedin.com/in/shreyash-khandagale-5824a5227/",
    instagram: "https://www.instagram.com/shreyash_sk_07",
  },
  {
    img: "/Developers/Yash.jpg",
    name: "Yash Waghmare",
    Profession: "WebMaster",
    git: "https://github.com/Yash-Waghmare",
    linkdin: "https://www.linkedin.com/in/yash-waghmare-7b8b51201/",
    instagram: "https://instagram.com/yash_7714?igshid=ZDdkNTZiNTM=",
  },
  {
    img: "/Developers/Suraj.jpg",
    name: "Suraj Tade",
    Profession: "WebMaster",
    git: "github.com/surajTade",
    linkdin: "https://www.linkedin.com/in/suraj-tade",
    instagram: " https://instagram.com/suraj__tade?igshid=ZDdkNTZiNTM=",
  },
  {
    img: "/Developers/sarthak2.jpeg",
    name: "Sarthak Joshi",
    Profession: "Developer",
    git: "https://github.com/sarthak-subhash-joshi",
    linkdin: "https://www.linkedin.com/in/sarthak-joshi-6112b7231/",
    instagram: "https://www.instagram.com/sarthak_joshi_3011/",
  },
  {
    img: "/Developers/girishnew.jpeg",
    name: "Girish Bhosale",
    Profession: "Developer",
    git: "https://github.com/Girish345",
    linkdin: "https://www.linkedin.com/in/girish-bhosale-876b2121b/",
    instagram: "https://www.instagram.com/__girish__39/",
  },
  {
    img: "/Developers/Atharva.jpg",
    name: "Atharva Pande",
    Profession: "Developer",
    git: "https://github.com/atharvapande45",
    linkdin: "https://www.linkedin.com/in/atharva-pande-855341244",
    instagram: "https://instagram.com/atharvapande45?igshid=ZDdkNTZiNTM=",
  },
  {
    img: "/Developers/aditya.jpg",
    name: "Aditya Lad",
    Profession: "Jr. WebMaster",
    git: "https://github.com/Adityalad-25",
    linkdin: "https://www.linkedin.com/in/aditya-lad-609586226",
    instagram: "https://instagram.com/_adi_ty_a?igshid=ZDdkNTZiNTM=",
  },
  {
    img: "/Developers/sejal.jpg",
    name: "Sejal Rahane",
    Profession: "Jr. WebMaster",
    git: "https://github.com/sejalrahane",
    linkdin: "https://www.linkedin.com/in/sejal-rahane-094447193",
    instagram: "https://instagram.com/sejal_rahane_?igshid=MTA2NDdkNWE=",
  },
  {
    img: "/Developers/Chetan.jpg",
    name: "Chetan Padhen",
    Profession: "Jr. WebMaster",
    git: " https://github.com/Chetax",
    linkdin: "https://www.linkedin.com/in/chetan-padhen-501416222/",
    instagram: "",
  },
  {
    img: "/Developers/mrudul.jpg",
    name: "Mrudul Ahirrao",
    Profession: "Jr. WebMaster",
    git: "https://github.com/MrudulAhirrao",
    linkdin: "https://in.linkedin.com/in/mrudul-ahirrao-133088216",
    instagram: "https://www.instagram.com/mrudul.ahirrao/",
  },
  {
    img: "/Developers/pranav.jpeg",
    name: "Pranav Kulkarni",
    Profession: "Jr. WebMaster",
    git: "https://www.github.com/pranavkulkarni2905",
    linkdin: "https://www.linkedin.com/in/pranavk2905",
    instagram: "https://instagram.com/i_am_pranavkulkarni?igshid=ZDdkNTZiNTM=",
  },
  {
    img: "/Developers/shraddha.jpg",
    name:"Shradha Yeole",
    Profession: "Jr. WebMaster",
    git: "https://github.com/MrudulAhirrao",
    linkdin: "https://www.linkedin.com/in/shraddha-yeole-8519161b4/",
    instagram: "https://instagram.com/shradha_1602?igshid=ZDdkNTZiNTM=",
  },
  {
    img: "/Developers/Tarun.jpeg",
    name: "Tarun Rathod",
    Profession: "Jr. WebMaster",
    git: "https://github.com/tarunnnrathoddd",
    linkdin: "https://www.linkedin.com/in/tarun-rathod-aa7ab7223",
    instagram: "https://www.instagram.com/_.tarunnn.rathoddd._",
  },
  {
    img: "/Developers/Kanak.jpg",
    name: "Kanak Agarwal",
    Profession: "Jr. WebMaster",
    git: "https://github.com/kanak8403",
    linkdin: "https://www.linkedin.com/in/kanak-agrawal-78791a259/",
    instagram: "https://www.instagram.com/kanakagrawal08/. ",
  },
  {
    img: "/Developers/vaishnavi.jpeg",
    name: "Vaishnavi Jadhav",
    Profession: "Marketing OWASP",
    git: "",
    linkdin: "https://www.linkedin.com/in/vaishnavi-jadhav-3b6abb250/",
    instagram: "",
  },
  {
    img: "/Developers/Bhumika.jpg",
    name: "Bhumika Patil",
    Profession: "WebMaster",
    git: "http://github.com/Bhumi9403",
    linkdin: "http://linkedin.com/in/bhumika-patil-77a8a5220/",
    instagram: "http://instagram.com/_bhumikapatil_2003/",
  },{
    img: "/Developers/Yash_patel.jpg",
    name: "Yash Patel",
    Profession: "Marketing OWASP",
    git: "https://github.com/Yaaashh",
    linkdin: "https://www.linkedin.com/in/yash-patel-80615b20a",
    instagram: "https://instagram.com/__yaaashh__?igshid=ZDdkNTZiNTM=",
  },
  {
    img: "/Developers/sarthak_zambre.JPG",
    name: "Sarthak Zambre",
    Profession: "Treasurer",
    git: "https://github.com/kanak8403",
    linkdin: "https://www.linkedin.com/in/sarthakzambre",
    instagram: "https://instagram.com/sarthakz_9?igshid=YmMyMTA2M2Y=",
  },
  {
    img: "/Developers/Kartik_chaudhari.jpg",
    name: "Kartik Chaudhari",
    Profession: "Secretary",
    git: "https://github.com/Kartik1646",
    linkdin: "https://www.linkedin.com/in/kartik-chaudhari-39a872209",
    instagram: "https://www.instagram.com/_kartik.56",
  },
  {
    img: "/Developers/mukgdha.jpg",
    name: "Mugdha kshirsagar",
    Profession: "HSC Head",
    git: "https://github.com/mugdhaK21",
    linkdin: "https://www.linkedin.com/in/mugdha-kshirsagar-6400a31ba/",
    instagram: "https://instagram.com/mk_mugdha_21?igshid=ZDdkNTZiNTM=",
  },
  {
    img: "/Developers/vallabh.png",
    name: "Vallabh Kulkarni",
    Profession: "Social Media",
    git: "https://github.com/tastycoderop",
    linkdin: "https://www.linkedin.com/in/vallabh-kulkarni984857/",
    instagram: "https://www.instagram.com/itsvallabh/",
  },
  {
    img: "/Developers/Aniket.jpg",
    name: "Aniket Choudhar",
    Profession: "Sports Cell",
    git: "https://github.com/AniketC007",
    linkdin: "https://www.linkedin.com/in/vallabh-kulkarni984857/",
    instagram: "https://www.instagram.com/aniket___0007/",
  },
  {
    img: "/Developers/Tirthesh.jpeg",
    name: "Tirthesh Patange",
    Profession: "Photograpy Cell",
    git: "https://github.com/tiirthesh",
    linkdin: "https://www.linkedin.com/in/tirthesh121",
    instagram: "instagram.com/tiirthesh",
  },
  {
    img: "/Developers/aray_kaslikar.jpg",
    name: "Arya Kaslikar",
    Profession: "OWASP Lead",
    git: "https://github.com/AryaK-31",
    linkdin: "https://www.linkedin.com/in/arya-kaslikar-bb6957268/",
    instagram: "http://instagram.com/tiirthesh",
  },
  {
    img: "/Developers/khush.jpg",
    name: "Khush Kothari",
    Profession: "Marketting Head",
    git: "https://www.linkedin.com/in/khush-kothari-6991b7213",
    linkdin: "https://www.linkedin.com/in/khush-kothari-6991b7213",
    instagram: "https://drive.google.com/open?id=1izVryZSdBWp2x7d1ImjhNxyp9BdDHj6j",
  },
  {
    img: "/Developers/mahima.jpg",
    name: "Mahima Nair",
    Profession: "Management Head",
    git: "https://github.com/mahima-nair",
    linkdin: "https://www.linkedin.com/in/mahima-nair-8995b823b/",
    instagram: "",
  },
  {
    img: "/Developers/ankita.jpg",
    name: "Ankita Nandy",
    Profession: "Social Media",
    git: "https://github.com/ankitanandy2608",
    linkdin: "https://www.linkedin.com/in/mahima-nair-8995b823b/",
    instagram: "https://www.instagram.com/ankita_nandy/",
  },
  {
    img: "/Developers/shrushti.JPG",
    name: "Shrushti Khirwadkar ",
    Profession: "HSC head",
    git: "https://github.com/shrushti-02",
    linkdin: "https://www.linkedin.com/in/shrushti-k-29726520a",
    instagram: "https://instagram.com/kshrushti_?igshid=ZDdkNTZiNTM=",
  },
  {
    img: "/Developers/Sahil_bomble.JPG",
    name: "Sahil Bomble",
    Profession: "Security Team",
    git: "https://github.com/Justsah1l",
    linkdin: "https://www.linkedin.com/in/sahil-bomble-0432a01b9",
    instagram: "https://www.instagram.com/justsahil._/",
  },
  {
    img: "/Developers/sahil.jpg",
    name: "Sahil Dhanwani",
    Profession: "Event Co-ordinator",
    git: "https://github.com/SahilDhanwani",
    linkdin: "https://www.linkedin.com/in/sahil-dhanwani-37825822b",
    instagram: "https://instagram.com/sahil_dhanwani3260?igshid=ZDdkNTZiNTM=",
  },
  {
    img: "/Developers/Vishakha.jpeg",
    name: "Vishakha Deshpande ",
    Profession: "Jr. Secretary ",
    git: "https://github.com/VishhAAkha",
    linkdin: "https://www.linkedin.com/in/vishakha-deshpande-152a5b230",
    instagram: "https://instagram.com/vishhaakhaa?igshid=ZDdkNTZiNTM=",
  },
  {
    img: "/Developers/mahesh.jPG",
    name: "Mahesh Yarra",
    Profession: "Marketing Head",
    git: "https://github.com/Mahesh-Yarra",
    linkdin: "https://www.linkedin.com/in/mahesh-yarra-997963214/",
    instagram: "https://www.instagram.com/mahes_._hhh/",
  },
  {
    img: "/Developers/radhika.jpeg",
    name: "Radhika Gaikwad ",
    Profession: "Social Media head ",
    git: "https://github.com/radsss16",
    linkdin: "https://www.linkedin.com/in/radhika-gaikwad-0372a5202",
    instagram: "https://instagram.com/radhikaaa_g?igshid=YmMyMTA2M2Y=",
  },
  // {
  //   img: "/Developers/aditya_agre.jpeg",
  //   name: "Aditya Agre",
  //   Profession: "Management head GDSC",
  //   git: "https://github.com/adityaagre",
  //   linkdin: "https://www.linkedin.com/in/aditya-agre-816558220/",
  //   instagram: "https://www.instagram.com/_adityaagre_/",
  // },
  // {
  //   img: "/Developers/tanmay.jpg",
  //   name: "Tanmay Jain ",
  //   Profession: "Photography Cell Head",
  //   git: "",
  //   linkdin: "https://www.linkedin.com/in/tanmay-jain-3a8243223",
  //   instagram: "https://instagram.com/skywalker_.15?igshid=ZDdkNTZiNTM=",
  // },
  {
    img: "/Developers/prathamesh.jpeg",
    name: "Prathamesh Bachhav",
    Profession: "SY Management head",
    git: "http://github.com/itspratham02",
    linkdin: "http://linkedin.com/in/prathamesh-bachhav-282b11229",
    instagram: "https://instagram.com/itspratham_02?igshid=YmMyMTA2M2Y=",
  },
  {
    img: "/Developers/saie.jpg",
    name: "Saie Mukane ",
    Profession: "PR executive ",
    git: "",
    linkdin: "https://www.linkedin.com/in/saie-mukane-242562229",
    instagram: "https://instagram.com/_saieee?igshid=MGNiNDI5ZTU=",
  },
  // {
  //   img: "/Developers/",
  //   name: "",
  //   Profession: "",
  //   git: "",
  //   linkdin: "",
  //   instagram: "",
  // },
  // {
  //   img: "/Developers/",
  //   name: "",
  //   Profession: "",
  //   git: "",
  //   linkdin: "",
  //   instagram: "",
  // },
  // {
  //   img: "/Developers/",
  //   name: "",
  //   Profession: "",
  //   git: "",
  //   linkdin: "",
  //   instagram: "",
  // },
];

export default TeamData;
